import React from 'react'

export default [
  {
    path: '/',
    component: () => <div>
      <div>asdfasdf</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
      <div>asdfasdfd</div>
    </div>,
  }
]
